name: guilds
version: '1.0.0'
main: de.mcterranova.guilds.Guilds
api-version: '1.21'
authors: [ Bastizeit ]
softdepend:
  - Vault
  - Citizens
commands:
  guild:
    description: Gilden-Commands
    usage: /guild
    permission: guild.use
  guildadmin:
    description: Admin commands for guild setup
    usage: /guildadmin
    permission: guild.admin